Enhance ppa tests
corona-warn-app/cwa-ppa-server pull request #135
Opened 2021-02-25 08:54 UTC by EugenM-SAP

2021-02-26 10:30 UTC, sorin-stefan-iovita-sap approved these changes

2021-02-26 14:13 UTC, hilmarf commented on common/persistence/src/test/java/app/coronawarn/datadonation/common/persistence/service/PpaDataServiceTest.java
> +import static org.mockito.Mockito.mock;import java.time.LocalDate;
```suggestion
import static org.mockito.Mockito.mock;

import java.time.LocalDate;
```

2021-02-26 14:16 UTC, hilmarf commented on services/ppac/src/test/java/app/coronawarn/datadonation/services/ppac/android/testutils/AndroidTestUtils.java
> +}
what's this good for?

2021-02-28 15:13 UTC, hilmarf approved these changes

2021-03-02 08:12 UTC, hilmarf requested changes
checkResponseStatusForValidNonce is failing

2021-03-02 08:12 UTC, hilmarf commented on services/ppac/src/test/java/app/coronawarn/datadonation/services/ppac/android/controller/AndroidControllerTest.java
>      }
@EugenM-SAP can you please check why this test doesn't pass in CircleCi build?

2021-03-15 13:01 UTC, hilmarf approved these changes

2021-03-15 14:46 UTC, merged